### ISSUE TITLE
while block is code that doesn't work? 

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ruby#7]
I don't think this code actually runs:
```ruby
while i < 10 do |i|
  i += 1
end
```
NoMethodError: undefined method `+' for nil:NilClass
Am I missing something?

**Comment by payne-chris-r** [comment]
Suggestion?

``` ruby
i = 1
while i < 10 do
  i += 1
end
```

**Comment by raq929** [comment]
Not sure why this didn't close with the commit.
